### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by alerque** [reviewdog/action-vint#6]
This action never returns fail results even with known linting issues.

**Comment by haya14busa** [comment]
Please be more specific. Does the know listing issues is in Pull Request diff?

**Comment by alerque** [comment]
I was unaware until your comment that this plugin would only act on issues present in the diff. I was testing with new projects. I'll test with introducing a new linting error in a diff now.

**Comment by alerque** [comment]
I can confirm this does work, it just wasn't expected that it ONLY‌works in the PR diff, not on the whole project. Cool feature, but could be more explicitly documented.

**Comment by haya14busa** [comment]
https://github.com/reviewdog/reviewdog#filter-mode

**Comment by haya14busa** [comment]
You can change filter-mode to configure the filtering mode.
